### ISSUE TITLE
[motion] Not support the spring of transition

### ISSUE THREAD

**Issue by YeSuX** [oku-ui/motion#14]
### Clear and concise description of the problem

<img width="477" alt="image" src="https://github.com/oku-ui/motion/assets/44074974/f8a4407a-a6ac-4b9c-b347-d8f67b78f779">
can't Implement

### Suggested solution

<img width="566" alt="image" src="https://github.com/oku-ui/motion/assets/44074974/1ea2dd54-90f6-4bf2-8050-776912c6d8ca">

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by productdevbook** [comment]
now supported. with version 0.4.0.
