### ISSUE TITLE
Internal server error: Failed to resolve import "../context"

### ISSUE THREAD

**Issue by Mehdi-Hp** [oku-ui/motion#23]
### Describe the bug

Vite throws and error that says:

```
[plugin:vite:import-analysis] Failed to resolve import "../context" from "../node_modules/.pnpm/@oku-ui+motion@0.3.2_vue@3.4.6/node_modules/@oku-ui/motion/dist/component/PresenceGroup.vue". Does the file exist?
```
It happens for `PresenceGroup.vue`/`Presence.vue`/`Motion.vue`.

If I add extension to the import statement and change `import { presenceId } from '../context'` to `import { presenceId } from '../context.mjs'`, it workes.

---

This is probably an issue with `unbuild` package, but seems to be fixed in version 2.0.0 and I couldn't figure out what version you're using to build the lib.  

https://github.com/unjs/mkdist/issues/45
https://github.com/unjs/unbuild/issues/83

### System Info

```Shell
System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 128.70 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.9.0 - ~/.proto/shims/node
    npm: 10.2.4 - /opt/homebrew/bin/npm
    pnpm: 8.10.2 - ~/.proto/shims/pnpm
  Browsers:
    Chrome: 120.0.6099.216
    Safari: 17.2.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/productdevbook/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by productdevbook** [comment]
can you share a sample repo or stackblitz ?

**Comment by Mehdi-Hp** [comment]
Turns out it was because of my `resolve.extensions` config in `vite.config.ts`.  
Before → `resolve: { extensions: ['.js', '.ts', '.vue', '.css', '.postcss'] }`
After → `resolve: { extensions: ['.js', '.ts', '.vue', '.css', '.postcss', '.mjs'] }`

The default value also works, as it sets to `['.mjs', '.js', '.mts', '.ts', '.jsx', '.tsx', '.json']`

**Comment by productdevbook** [comment]
Thank you for writing wonderfully detailed explanations.
