### ISSUE TITLE
Missing required props warning for <Presence />

### ISSUE THREAD

**Issue by khang-nd** [oku-ui/motion#36]
https://github.com/oku-ui/motion/blob/584e368e13cd3a63f56072f0a7c4c4e48731f822/packages/vue/src/components/Presence.vue#L23-L27

I suppose `exitBeforeEnter` and `initial` should be declared optional to suppress this warning and align with the docs.

**Comment by zernonia** [comment]
Any update for this @YeSuX ? 😁

**Comment by productdevbook** [comment]
@zernonia :D He is very busy and can't take care of the library, so I will take a look at this.

**Comment by productdevbook** [comment]
In 2 days I will release the new version.
