### ISSUE TITLE
Question: any plans to add animate function?

### ISSUE THREAD

**Issue by jupelost** [oku-ui/motion#45]
### Clear and concise description of the problem

Are there any plans to add this?

### Suggested solution

https://motion.dev/dom/animate
https://www.framer.com/motion/use-animate/

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by productdevbook** [comment]
We need to add them all, actually. If you have the means, don't hesitate to send pr. Thank you ❤️

**Comment by productdevbook** [comment]
I'm working on it. It'll be here soon.
