### ISSUE TITLE
support svg path d animation

### ISSUE THREAD

**Issue by imfenghuang** [oku-ui/motion#53]
### Clear and concise description of the problem

![image](https://github.com/user-attachments/assets/6fb5920f-e96b-46ec-a281-db0b5111647b)

when i set `d` and want it be animated, however it got warnings

### Suggested solution

can this lib support it?
now it only support dom styles

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by productdevbook** [comment]
Yes we will support this. https://github.com/oku-ui/motion/issues/26 similar issua. Can you send me a sample code. I'll add it to my playground.

**Comment by imfenghuang** [comment]
sample code: https://stackblitz.com/edit/vitejs-vite-1d9rf1?file=src%2FApp.vue

**Comment by productdevbook** [comment]
Version 0.4.0 has been published!

Could you review your code based on the updated usages and examples provided in the [documentation](https://motion.oku-ui.com/components/motion-component#path)? Additionally, please include TailwindCSS in the demo, as the CSS codes are not functioning properly.

**Comment by imfenghuang** [comment]
after update to  0.4.0 it worked

let me try others

**Comment by productdevbook** [comment]
can you share your examples with us?

**Comment by imfenghuang** [comment]
> can you share your examples with us?
yeah, of course.
i'm preparing a repo with `@oku-ui/motion`, some case code need to be rewritten, please wait a moment 😊
