### ISSUE TITLE
a

### ISSUE THREAD

**Issue by productdevbook** [oku-ui/motion#55]

**Comment by productdevbook** [comment]
cc: @rick-hup

**Comment by rick-hup** [comment]
I'm trying to develop a motion-vue library with an API that stays as consistent as possible with framer-motion, purely as a practice exercise. Since this is just for practice, I might modify the code freely. However, if this were for an open source project, there would likely be many more constraints to consider.

**Comment by productdevbook** [comment]
Hey @rick-hup, thanks for the quick reply! 😊

I completely understand your approach—working on a motion-vue library to match Framer Motion is a great practice exercise! I’m excited about the opportunity to merge our ideas, and I think it could be really beneficial to combine our efforts here. If you’re open to it, we can start by exploring how our codebases align and see where we can make adjustments to keep things as streamlined as possible.

No pressure to make any immediate changes if it’s just for practice. But, if you’d like to contribute or share your work for feedback, I’d love to help out! Looking forward to collaborating.

I’ve copied your code into a new bracnh and made some improvements. I’ve added the changes and improvements to the README description. These updates are currently available in [branch](https://github.com/oku-ui/motion/tree/refactor-motion)

Looking forward to your thoughts. I’d be happy to consider any feedback you have. Thanks!

**Comment by productdevbook** [comment]
We will be waiting for you in the future. Thank you for all your work.
