### ISSUE TITLE
AvatarFallback.mjs issue on production.

### ISSUE THREAD

**Issue by NikitaVelixJob** [oku-ui/motion#68]
### Describe the bug

Hello!

On production I have an issue with AvatarFallback.mjs

Cannot find module '/app/.output/server/node_modules/@oku-ui/primitives/dist/node_modules/.pnpm/@vueuse_shared@11.2.0_vue@3.5.13_typescript@5.6.3_/node_modules/@vueuse/shared/index.mjs' imported from /app/.output/server/node_modules/@oku-ui/primitives/dist/avatar/AvatarFallback.mjs

Nuxt 3.14.1592 with SSR, on first load.
I also have installed @vueuse/motion.

In Reproduction do the build and run npx nuxi preview (node .output/server/index.mjs)

### Reproduction

https://stackblitz.com/edit/nuxt-starter-yw2xh5?file=app.vue

### System Info

```Shell
System:
    OS: macOS 15.1
    CPU: (12) arm64 Apple M3 Pro
    Memory: 230.42 MB / 18.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.5.0 - ~/.nvm/versions/node/v21.5.0/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v21.5.0/bin/npm
    pnpm: 9.1.4 - ~/.nvm/versions/node/v21.5.0/bin/pnpm
    bun: 1.0.20 - ~/.bun/bin/bun
  Browsers:
    Brave Browser: 125.1.66.118
    Chrome: 130.0.6723.117
    Edge: 121.0.2277.83
    Safari: 18.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/productdevbook/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by NikitaVelixJob** [comment]
Thank you @productdevbook. 
can you also change the name of nuxt config from motion to okuMotion, because its overlaps with motion of vueuse?

**Comment by NikitaVelixJob** [comment]
Wanted to do a pr for that, but dont know how to test the builded local project with it.

**Comment by NikitaVelixJob** [comment]
@productdevbook its the same, Avatar fallback on build :(


[nuxt] [request error] [unhandled] [500] Cannot find module '/home/projects/nuxt-starter-yw2xh5/.output/server/node_modules/@oku-ui/primitives/dist/node_modules/.pnpm/@vueuse_shared@11.2.0_vue@3.5.13_typescript@5.6.3_/node_modules/@vueuse/shared/index.mjs' imported from /home/projects/nuxt-starter-yw2xh5/.output/server/node_modules/@oku-ui/primitives/dist/avatar/AvatarFallback.mjs

**Comment by productdevbook** [comment]
I'll take a look at it. I see your problem.

**Comment by productdevbook** [comment]
`0.4.3` version fixed. Thank you.

**Comment by NikitaVelixJob** [comment]
It fixed, thank you Mehmet!
