### ISSUE TITLE
[motion] Keyframes can't work

### ISSUE THREAD

**Issue by YeSuX** [oku-ui/motion#8]
### Describe the bug

When using an array in animation, the animation will no longer work.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-qfhz8t?file=src%2FDemo.vue

### System Info

```Shell
OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
    pnpm: 8.14.0 - /usr/local/bin/pnpm
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/productdevbook/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by productdevbook** [comment]
https://stackblitz.com/edit/vitejs-vite-slwxwf?file=src%2Fmain.ts

v0.4.0 with it works now.
